### ISSUE TITLE
Areas of improvement in framework building

### ISSUE THREAD

**Issue by p00j4** [GvvPrasad/Basic_Framework_Structure#1]
1. Overall 
Improve your code's readability and quality. 
- Use meaningful class name (generally noun)
- Use meaningful function name (generally verb, camle cased starting with small case)
- A function should only what it's name say. Any dependent computation to go in a new function. (right now you are having one lengthy function)
- Use meaningful variable names and starting with small case letters (locator names are also variable names in your case)
- Use proper docstring (comments) explaining what your function is doing, what will it return etc.

2. Add separate utility classes for all needed functionality for testing. Your test class should only focus on called or inheriting those util functions and do asserts (which is your business logic)

3. Instead of dead sleeps try different wait mechanisms as suitable. FluentWait is much useful. https://github.com/GvvPrasad/Framework_Structure/blob/a739387ca09a49a01afaf54b5da8c6219219c4cf/src/test/java/Test_Scripts/Salary_Comp.java#L25

4. Why repetitive excel reading? make a reusable function and infact call at beginning once to get complete excel read and fed to your variables passed on to tests using getters and setters may be https://github.com/GvvPrasad/Framework_Structure/blob/a739387ca09a49a01afaf54b5da8c6219219c4cf/src/test/java/Test_Scripts/Salary_Comp.java#L28

5. For practise it's ok however there is no need to git push the test-output dir. You can add to .gitignore file. 

6. For easing up things, believe in practicing Coding and utilise Java's inheritance, interface and design patterns first. That will make you automatically stronger at all things mentioned above. 

For reference: This is a good resource https://github.com/testvagrant/cleartriptests

**Comment by GvvPrasad** [comment]
Working on the Issue and Improvements in the Repository with name "frameworkStructure" 
https://github.com/GvvPrasad/frameworkStructure
